apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fne2gb8cz-nodejs
  janus-idp.io/tekton: fne2gb8cz-nodejs
  backstage.io/kubernetes-id: fne2gb8cz-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fne2gb8cz-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
